layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Spring Cloud
    web_url: https://github.com/spring-cloud
    image_url: https://avatars3.githubusercontent.com/u/7815877?s=200&v=4

  - name: ReactJS
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

  - name: Spring Boot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

  - name: Python
    web_url: https://github.com/topics/python3
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: Awesome
    web_url: https://github.com/topics/awesome
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/awesome/awesome.png

